register_cutter('default:stone', 'default:stone_brick')
register_cutter('default:stone', 'default:stone_smooth')
register_cutter('default:stone', 'default:stone_pillar')
register_cutter('default:stone', 'default:stone_pillar_edge')
register_cutter('default:cobble', 'default:stone_brick')
register_cutter('default:cobble', 'default:stone_smooth')
register_cutter('default:apple_tree', 'default:wood 6')
register_cutter('default:oak_tree', 'default:oak_wood 6')
register_cutter('default:birch_tree', 'default:birch_wood 6')